server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${catalog.datasource.driver-class-name}
      url: jdbc:mysql://${catalog.datasource.host}:${catalog.datasource.port}/${catalog.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${catalog.datasource.username}
      password: ${catalog.datasource.password}
  redis:
    host: ${catalog.redis.host}
    port: ${catalog.redis.port}
    password: ${catalog.redis.password}
    database: ${catalog.redis.database}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.catalog.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      catalog:
        mapper: debug
        service: info
        controller: info

catalog:
  jwt:
    admin-secret-key: FzuCreature
    admin-ttl: 72000000
    admin-token-name: token
    user-secret-key: FzuCatalog
    user-ttl: 72000000
    user-token-name: authentication
  wechat:
    appid: ${catalog.wechat.appid}
    secret: ${catalog.wechat.secret}
