catalog:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: fzuCatalog
    username: root
    password: root
    schema: 111
    data: 111
  redis:
    host: localhost
    port: 6379
    password: root
    database: 5
  wechat:
    secret:
    appid:
    login-url: https://api.weixin.qq.com/sns/jscode2session
  img:
    url: https://mlws2s3e.cfornas.casa:8443/api/v1
    email:
    password:
